export const USER_DATA_LOADING = 'USER_DATA_LOADING'
export const USER_DATA_SUCCESS = 'USER_DATA_SUCCESS'
export const USER_DATA_FAILED = 'USER_DATA_FAILED'

export const USER_PASSWORD_CHANGE_LOADING = 'USER_PASSWORD_CHANGE_LOADING'
export const USER_PASSWORD_CHANGE_SUCCESS = 'USER_PASSWORD_CHANGE_SUCCESS'
export const USER_PASSWORD_CHANGE_FAILED = 'USER_PASSWORD_CHANGE_FAILED'

export const LOGIN_LOADING = 'LOGIN_LOADING'
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'
export const LOGIN_FAILED = 'LOGIN_FAILED'

export const SIGNUP_LOADING = 'SIGNUP_LOADING'
export const SIGNUP_SUCCESS = 'SIGNUP_SUCCESS'
export const SIGNUP_FAILED = 'SIGNUP_FAILED'

export const GET_EVENT_LOADING = 'GET_EVENT_LOADING'
export const GET_EVENT_SUCCESS = 'GET_EVENT_SUCCESS'
export const GET_EVENT_FAILED = 'GET_EVENT_FAILED'

export const CREATE_EVENT_LOADING = 'CREATE_EVENT_LOADING'
export const CREATE_EVENT_SUCCESS = 'CREATE_EVENT_SUCCESS'
export const CREATE_EVENT_FAILED = 'CREATE_EVENT_FAILED'

export const DELETE_EVENT_LOADING = 'DELETE_EVENT_LOADING'
export const DELETE_EVENT_SUCCESS = 'DELETE_EVENT_SUCCESS'
export const DELETE_EVENT_FAILED = 'DELETE_EVENT_FAILED'

export const EDIT_EVENT_LOADING = 'EDIT_EVENT_LOADING'
export const EDIT_EVENT_SUCCESS = 'EDIT_EVENT_SUCCESS'
export const EDIT_EVENT_FAILED = 'EDIT_EVENT_FAILED'

export const EVENT_SUCCESS_RESET = 'EVENT_SUCCESS_RESET'
export const CHANGE_FIELDS = 'CHANGE_FIELDS'
export const CLEAR_FIELDS = 'CLEAR_FIELDS'
export const USER_LOGOUT = 'USER_LOGOUT'
